#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/run_fedavg_local.sh
#   CLIENTS=10 ROUNDS=50 LOCAL_EPOCHS=1 ./scripts/run_fedavg_local.sh
#
# Requires:
#   outputs/central_vendor.pt (generated by run_central.sh)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PYTHON_BIN="${PYTHON_BIN:-python3}"
DATA_DIR="${DATA_DIR:-./data}"
OUT_DIR="${OUT_DIR:-./outputs}"
VENDOR_CKPT="${VENDOR_CKPT:-$OUT_DIR/central_vendor.pt}"

CLIENTS="${CLIENTS:-10}"
ROUNDS="${ROUNDS:-50}"
BATCH="${BATCH:-64}"
LR="${LR:-0.01}"
LOCAL_EPOCHS="${LOCAL_EPOCHS:-1}"
SEED="${SEED:-42}"

SERVER_HOST="${SERVER_HOST:-127.0.0.1}"
SERVER_PORT="${SERVER_PORT:-8080}"
SERVER_ADDR="${SERVER_HOST}:${SERVER_PORT}"

mkdir -p "$DATA_DIR" "$OUT_DIR"

if [[ ! -f "$VENDOR_CKPT" ]]; then
  echo "[run_fedavg_local] ERROR: vendor checkpoint not found: $VENDOR_CKPT"
  echo "Run: ./scripts/run_central.sh first"
  exit 1
fi

# Cleanup handler
PIDS=()
cleanup() {
  echo ""
  echo "[run_fedavg_local] Cleaning up..."
  for pid in "${PIDS[@]:-}"; do
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
    fi
  done
  # Give processes a moment, then force kill if needed
  sleep 1 || true
  for pid in "${PIDS[@]:-}"; do
    if kill -0 "$pid" 2>/dev/null; then
      kill -9 "$pid" 2>/dev/null || true
    fi
  done
  echo "[run_fedavg_local] Cleanup done."
}
trap cleanup EXIT INT TERM

echo "[run_fedavg_local] Starting server at $SERVER_ADDR"
"$PYTHON_BIN" server_app.py \
  --addr "0.0.0.0:${SERVER_PORT}" \
  --vendor_ckpt "$VENDOR_CKPT" \
  --clients "$CLIENTS" \
  --rounds "$ROUNDS" \
  --out_dir "$OUT_DIR" \
  --seed "$SEED" \
  > "$OUT_DIR/server.log" 2>&1 &
SERVER_PID=$!
PIDS+=("$SERVER_PID")

# Wait briefly for server to start
sleep 2

echo "[run_fedavg_local] Starting $CLIENTS clients..."
for ((cid=0; cid<CLIENTS; cid++)); do
  "$PYTHON_BIN" client_app.py \
    --cid "$cid" \
    --server "$SERVER_ADDR" \
    --data_dir "$DATA_DIR" \
    --clients "$CLIENTS" \
    --batch "$BATCH" \
    --lr "$LR" \
    --local_epochs "$LOCAL_EPOCHS" \
    --seed "$SEED" \
    > "$OUT_DIR/client_${cid}.log" 2>&1 &
  PIDS+=("$!")
done

echo "[run_fedavg_local] Running. Logs: $OUT_DIR/server.log, $OUT_DIR/client_*.log"
echo "[run_fedavg_local] Waiting for server to finish rounds=$ROUNDS ..."

# Wait for server; clients will exit when server stops
wait "$SERVER_PID"

echo "[run_fedavg_local] Server finished."
echo "[run_fedavg_local] Expected output model: $OUT_DIR/fedavg_global.pt"
