#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/run_local_only.sh
#   CLIENTS=10 EPOCHS=50 ./scripts/run_local_only.sh
#
# Optional:
#   BATCH=64 LR=0.01 SEED=42 ./scripts/run_local_only.sh
#   NUM_WORKERS=4 PIN_MEMORY=1 ./scripts/run_local_only.sh
#
# Requires:
#   outputs/central_vendor.pt (generated by run_central.sh)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Prefer venv python if exists
if [[ -x ".venv/bin/python" ]]; then
  PYTHON_BIN=".venv/bin/python"
else
  PYTHON_BIN="${PYTHON_BIN:-python3}"
fi

DATA_DIR="${DATA_DIR:-./data}"
OUT_DIR="${OUT_DIR:-./outputs}"
VENDOR_CKPT="${VENDOR_CKPT:-$OUT_DIR/central_vendor.pt}"

CLIENTS="${CLIENTS:-10}"
EPOCHS="${EPOCHS:-50}"
BATCH="${BATCH:-64}"
LR="${LR:-0.01}"
SEED="${SEED:-42}"

# run_local.py supports these now
NUM_WORKERS="${NUM_WORKERS:-4}"
PIN_MEMORY="${PIN_MEMORY:-0}"   # 1 -> enable --pin_memory

mkdir -p "$DATA_DIR" "$OUT_DIR"

if [[ ! -f "$VENDOR_CKPT" ]]; then
  echo "[run_local_only] ERROR: vendor checkpoint not found: $VENDOR_CKPT"
  echo "[run_local_only] Hint: run ./scripts/run_central.sh first"
  exit 1
fi

PIN_ARG=()
if [[ "$PIN_MEMORY" == "1" ]]; then
  PIN_ARG+=(--pin_memory)
fi

echo "[run_local_only] python=$PYTHON_BIN"
echo "[run_local_only] vendor_ckpt=$VENDOR_CKPT"
echo "[run_local_only] clients=$CLIENTS epochs=$EPOCHS batch=$BATCH lr=$LR seed=$SEED"
echo "[run_local_only] num_workers=$NUM_WORKERS pin_memory=$PIN_MEMORY"
echo "[run_local_only] outputs: $OUT_DIR/local_metrics.csv, $OUT_DIR/local_clients.csv"
echo ""

"$PYTHON_BIN" run_local.py \
  --data_dir "$DATA_DIR" \
  --out_dir "$OUT_DIR" \
  --vendor_ckpt "$VENDOR_CKPT" \
  --clients "$CLIENTS" \
  --epochs "$EPOCHS" \
  --batch "$BATCH" \
  --lr "$LR" \
  --seed "$SEED" \
  --num_workers "$NUM_WORKERS" \
  "${PIN_ARG[@]}"

echo ""
echo "[run_local_only] Done."
echo "  - Summary:    $OUT_DIR/local_metrics.csv"
echo "  - Per-client: $OUT_DIR/local_clients.csv"
