#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/run_local_only.sh
#   CLIENTS=10 EPOCHS=50 ./scripts/run_local_only.sh
#
# Requires:
#   outputs/central_vendor.pt (generated by run_central.sh)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PYTHON_BIN="${PYTHON_BIN:-python3}"
DATA_DIR="${DATA_DIR:-./data}"
OUT_DIR="${OUT_DIR:-./outputs}"
VENDOR_CKPT="${VENDOR_CKPT:-$OUT_DIR/central_vendor.pt}"

CLIENTS="${CLIENTS:-10}"
EPOCHS="${EPOCHS:-50}"
BATCH="${BATCH:-64}"
LR="${LR:-0.01}"
SEED="${SEED:-42}"

mkdir -p "$DATA_DIR" "$OUT_DIR"

if [[ ! -f "$VENDOR_CKPT" ]]; then
  echo "[run_local_only] ERROR: vendor checkpoint not found: $VENDOR_CKPT"
  echo "Run: ./scripts/run_central.sh first"
  exit 1
fi

echo "[run_local_only] python=$PYTHON_BIN vendor_ckpt=$VENDOR_CKPT clients=$CLIENTS epochs=$EPOCHS batch=$BATCH lr=$LR seed=$SEED"

"$PYTHON_BIN" run_local.py \
  --data_dir "$DATA_DIR" \
  --out_dir "$OUT_DIR" \
  --vendor_ckpt "$VENDOR_CKPT" \
  --clients "$CLIENTS" \
  --epochs "$EPOCHS" \
  --batch "$BATCH" \
  --lr "$LR" \
  --seed "$SEED"

echo "[run_local_only] Done."
